# uosc
mbtn_right    script-binding uosc/menu
menu          script-binding uosc/menu
tab           script-binding uosc/toggle-ui
ctrl+k        script-binding uosc/keybinds
ctrl+e        script-binding subedit/subedit-open

# clip
c             script-binding clip/clip-mark-begin
C             script-binding clip/clip-mark-end
alt+c         script-binding clip/clip-create
alt+C         script-binding clip/clip-clear
alt+d         script-binding clip/clip-dest
