# =====================================
# ===           General             ===
# =====================================
set-option -g status off
set-option -g status-interval 1
set-option -g status-keys vi
set-option -g status-position bottom

# Set parent terminal title to reflect current window in tmux session
set -g set-titles on
set -g set-titles-string "#I:#W"

# =====================================
# ===           Keys                ===
# =====================================

# Helps when terminal window resizing breaks tmux's sizing
set-window-option -g aggressive-resize

# use ctrl-space as leader instead of ctrl-b
unbind C-b
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# =====================================
# ===           Mouse               ===
# =====================================
set -g mouse on

# more intuitive '|' for vert split and '-' for horiz split, and allow lowercase versions as well
bind '|' split-window -h -c "#{pane_current_path}"
bind '\' split-window -fh -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"
bind '_' split-window -fv -c "#{pane_current_path}"

# more intuitive resize keybindings
bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

# vim style bindings in scroll mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# easily reload plugins
bind r source-file "${TMUXDIR}/tmux.conf"

# =====================================
# ===         Plugin Setup          ===
# =====================================
# Where we are installing
set-environment -g TMUX_PLUGIN_MANAGER_PATH "${TMUX_PLUGIN_MANAGER_PATH}"

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_selection_mouse 'primary'

# ===            Themes             ===

# Dracula
# See https://draculatheme.com/tmux for config options
#set -g @plugin 'dracula/tmux'
#set -g @dracula-refresh-rate 2
#set -g @dracula-show-flags true
#set -g @dracula-show-ssh-session-port true
#set -g @dracula-git-show-current-symbol ✓
#set -g @dracula-git-no-repo-message ""
#set -g @dracula-git-show-remote-status true
#set -g @dracula-show-fahrenheit false
#set -g @dracula-fixed-location "Boston"

# tmux-power
#set -g @plugin 'wfxr/tmux-power'
#set -g @tmux_power_theme 'snow'
# TODO: Have this get right i3 icon
#set -g @tmux_power_session_icon ' '


# ===            Util               ===

# tpm
set -g @plugin 'tmux-plugins/tpm'

# sensible
set -g @plugin 'tmux-plugins/tmux-sensible'

# Git
set -g status-right '#(gitmux "#{pane_current_path}")'

# resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @resurrect-prefix '#S'
set -g @resurrect-show-session-prefix '1'
set -g @resurrect-processes 'watch nvidia-smi iotop'

# fzf
set -g @plugin 'sainnhe/tmux-fzf'

# Cheatsheet
set -g @plugin 'kenos1/tmux-cht-sh'

# Powerline
#run-shell "powerline-daemon -q"
#source "${HOME}/.local/lib/python${PYTHON_LIB_VER}/site-packages/powerline/bindings/tmux/powerline.conf"


# =====================================
# ===        Run Plugins            ===
# =====================================
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b "${TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm"

# Enable OSC 52 clipboard forwarding for remote Neovim yanks.
set -as terminal-features ",*:clipboard"
