#!/bin/bash
# workspace-map.sh - machine-agnostic workspace->monitor mapping.
#
# Modes (persisted in ~/.local/state/hypr/workspace-map-mode):
#   decade         10 workspaces per monitor: the bottom-right-most monitor
#                  gets 1-10, then 11-20 on the next monitor clockwise around
#                  the layout, and so on. With fewer monitors than decades the
#                  leftover decades round-robin (e.g. two monitors: 1-10/21-30
#                  and 11-20/31-40).
#   split          Odd workspaces on one display, even on the other (the old
#                  two-display system). Requires exactly two monitors.
#   split-flipped  Same with the two displays swapped.
#
# Commands:
#   apply   (default) compute the mapping for the current monitors, rewrite the
#           managed block in monitors.conf (survives hyprctl reload), apply the
#           rules live, and re-home any workspace sitting on the wrong monitor.
#           Never touches monitor lines, only its own marked block.
#   toggle  cycle decade -> split -> split-flipped -> decade
#   mode    print the current mode

set -o pipefail
CONF="$HOME/.config/hypr/monitors.conf"
STATE_DIR="$HOME/.local/state/hypr"
STATE_FILE="$STATE_DIR/workspace-map-mode"
BEGIN_MARK="# BEGIN workspace-map"
END_MARK="# END workspace-map"
WS_MAX=40

notify() {
  swayosd-client --custom-icon video-display --custom-message "$1" 2>/dev/null \
    || hyprctl notify -1 4000 0 "  $1  " >/dev/null
}

mode_get() { cat "$STATE_FILE" 2>/dev/null || echo decade; }
mode_set() { mkdir -p "$STATE_DIR" && echo "$1" > "$STATE_FILE"; }

monitor_count() { hyprctl monitors -j | jq '[.[] | select(.disabled == false)] | length'; }

# Monitor names ordered bottom-right-most first, then clockwise around the
# centroid of the layout (screen coordinates, y grows downward).
ordered_monitors() {
  hyprctl monitors -j | jq -r '
    def pi: 3.141592653589793;
    [.[] | select(.disabled == false)
         | {name, cx: (.x + (.width / .scale) / 2), cy: (.y + (.height / .scale) / 2)}] as $m
    | if ($m | length) == 0 then empty else
        (($m | map(.cx) | add) / ($m | length)) as $ccx
      | (($m | map(.cy) | add) / ($m | length)) as $ccy
      | ($m | map(. + {ang: atan2(.cy - $ccy; .cx - $ccx)})) as $ma
      | ($ma | max_by([.cy, .cx])) as $start
      | $ma
      | map(. + {rel: ((.ang - $start.ang) | if . < 0 then . + 2 * pi else . end)})
      | sort_by([.rel, .name])
      | .[].name
      end'
}

# Print one "workspace = N, monitor:X[, default:true]" line per workspace.
gen_rules() {
  local mode="$1"; shift
  local mons=("$@")
  local n=${#mons[@]} decades=$(( (WS_MAX + 9) / 10 ))
  local ws mon def d k
  if [[ $mode == split || $mode == split-flipped ]]; then
    local odd=${mons[0]} even=${mons[1]}
    if [[ $mode == split-flipped ]]; then odd=${mons[1]}; even=${mons[0]}; fi
    for ((ws = 1; ws <= WS_MAX; ws++)); do
      (( ws % 2 == 1 )) && mon=$odd || mon=$even
      def=""; (( ws <= 2 )) && def=", default:true"
      printf 'workspace = %d, monitor:%s%s\n' "$ws" "$mon" "$def"
    done
  else
    for ((d = 0; d < decades; d++)); do
      mon=${mons[$((d % n))]}
      for ((k = 1; k <= 10; k++)); do
        ws=$((d * 10 + k)); (( ws > WS_MAX )) && break
        def=""; (( k == 1 && d < n )) && def=", default:true"
        printf 'workspace = %d, monitor:%s%s\n' "$ws" "$mon" "$def"
      done
    done
  fi
}

# Replace (or append) the managed block in monitors.conf, leaving everything
# else in the file byte-for-byte intact apart from trailing blank lines.
write_block() {
  local mode="$1"; shift
  local body tmp
  body=$(awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
    index($0, b) == 1 { skip = 1; next }
    index($0, e) == 1 { skip = 0; next }
    !skip' "$CONF" 2>/dev/null)
  tmp=$(mktemp) || return 1
  {
    [[ -n $body ]] && printf '%s\n\n' "$body"
    printf '%s (mode: %s); generated by workspace-map.sh, do not hand-edit\n' "$BEGIN_MARK" "$mode"
    printf '%s\n' "$@"
    printf '%s\n' "$END_MARK"
  } > "$tmp" && cat "$tmp" > "$CONF"
  rm -f "$tmp"
}

apply_rules() {
  local line ws mon cur wsjson
  for line in "$@"; do
    hyprctl keyword workspace "${line#workspace = }" >/dev/null
  done
  # Re-home existing workspaces that sit on the wrong monitor (monitor drops
  # and mode changes scatter them; they never come back on their own).
  wsjson=$(hyprctl workspaces -j)
  for line in "$@"; do
    ws=${line#workspace = }; ws=${ws%%,*}
    mon=${line#*monitor:}; mon=${mon%%,*}
    cur=$(jq -r --argjson id "$ws" '.[] | select(.id == $id) | .monitor' <<<"$wsjson")
    if [[ -n $cur && $cur != "$mon" ]]; then
      hyprctl dispatch moveworkspacetomonitor "$ws" "$mon" >/dev/null
    fi
  done
}

cmd_apply() {
  local mode mons rules
  mode=$(mode_get)
  mapfile -t mons < <(ordered_monitors)
  (( ${#mons[@]} == 0 )) && exit 0
  if [[ $mode != decade ]] && (( ${#mons[@]} != 2 )); then
    mode=decade
    mode_set decade
  fi
  mapfile -t rules < <(gen_rules "$mode" "${mons[@]}")
  write_block "$mode" "${rules[@]}"
  apply_rules "${rules[@]}"
}

cmd_toggle() {
  local mode next
  mode=$(mode_get)
  case $mode in
    decade)
      if (( $(monitor_count) == 2 )); then
        next=split
      else
        notify "Odd/even split needs exactly two displays"
        exit 0
      fi ;;
    split) next=split-flipped ;;
    *) next=decade ;;
  esac
  mode_set "$next"
  cmd_apply
  case $next in
    decade)        notify "Workspaces: 10 per display" ;;
    split)         notify "Workspaces: odd/even split" ;;
    split-flipped) notify "Workspaces: odd/even split (flipped)" ;;
  esac
}

case "${1:-apply}" in
  apply)  cmd_apply ;;
  toggle) cmd_toggle ;;
  mode)   mode_get ;;
  *) echo "usage: $0 [apply|toggle|mode]" >&2; exit 1 ;;
esac
