# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,2

# Laptop display (default when no external monitor)
monitor = eDP-1, 2560x1600@180, -2x0, 1

monitor = HDMI-A-1, 2560x1440@119, 1600x0, 1.6
monitor = DP-2, 3840x2400@60, 1280x0, 1
monitor = DP-1, 1920x1080@60, -1200x0, 1.6
