export data="${HOME}/data/"
export dev="${HOME}/data/Documents/dev/"
export TMUXDIR="${HOME}/.config/tmux"
export TMUX_RESURRECT="${HOME}/.local/share/tmux/resurrect/"
export TMUX_PLUGIN_MANAGER_PATH="${TMUXDIR}/plugins"
