# TODO: find way to query xrandr here, e.g. some kind of
#   xrandr --listactivemonitors | awk '/\+/ {print $4}'
# to set values instead of hardcoding

# hardcoded displays...
set $m1 HDMI-0
set $m2 DP-4
set $m3 DP-2
set $m4 DP-0

# set brightness, red light etc
exec_always --no-startup-id $config/i3/scripts/monitors.sh

# Bind xsct temperature and brightness up down
bindsym $mod+$alt+Up exec xsct $(xsct | awk '{print $5 + 100}') $(xsct | awk '{print $6}')
bindsym $mod+$alt+Down exec xsct $(xsct | awk '{print $5 - 100}') $(xsct | awk '{print $6}')
bindsym $mod+$alt+Shift+Up exec xsct $(xsct | awk '{print $5}')  $(echo "$(xsct | awk '{print $6}') + 0.1" | bc)
bindsym $mod+$alt+Shift+Down exec xsct $(xsct | awk '{print $5}')  $(echo "$(xsct | awk '{print $6}') - 0.1" | bc)
