# feh shortcuts
bindsym $mod+n exec $config/i3/scripts/nsw.sh

bindsym $mod+Shift+s exec $config/i3/scripts/sanoid.sh

bindsym $mod+Shift+slash --whole-window exec $config/i3/scripts/open_default_programs/user_i3_help.sh

bindsym $mod+Shift+d exec firefox -ProfileManager

for_window [class="help-term_shortcuts"] floating enable, sticky enable, resize set 50 ppt 80 ppt, move position center
bindsym $mod+k exec $config/i3/scripts/fuzzy-helpers/help-term_shortcuts.sh

bindsym --release $mod+$caps+w exec xkill
