# Save screenshots as PNGs
screenshot-format=png
# Save screenshots in the same folder as the video
screenshot-directory=
# Custom screenshot filename template
screenshot-template=mpv_%F_%P_%ts
# Same bitrate as video
screenshot-high-bit-depth=yes
