# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no
# uosc will draw its own window controls and border if you disable window border
border=no
# Available: paused, audio, image, video, idle, windowed, fullscreen
#timeline_persistency=paused

osd-font-size=24
osd-scale-by-window=yes
#osd-scale-min=1.0
#osd-scale-max=3.0
osd-font='Fira Code Retina'
osd-status-msg=${playback-time/full} / ${duration} (${percent-pos}%) ${estimated-frame-number} / ${estimated-frame-count}
